//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackConverter.Res.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrackConverter.Res.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\{extension}]
        ///@=&quot;{name}&quot;
        ///
        ///[HKEY_CLASSES_ROOT\{name}]
        ///@=&quot;{comment}&quot;
        ///
        ///[HKEY_CLASSES_ROOT\{name}\CLSID]
        ///
        ///[HKEY_CLASSES_ROOT\{name}\DefaultIcon]
        ///@=&quot;\&quot;{exename}\&quot;,1&quot;
        ///
        ///[HKEY_CLASSES_ROOT\{name}\Shell]
        ///
        ///[HKEY_CLASSES_ROOT\{name}\Shell\Open]
        ///@=&quot;Открыть&quot;
        ///
        ///[HKEY_CLASSES_ROOT\{name}\Shell\Open\Command]
        ///@=&quot;\&quot;{exename}\&quot; &quot;%1&quot;&quot;.
        /// </summary>
        public static string associatereg_scheme_file {
            get {
                return ResourceManager.GetString("associatereg_scheme_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \Data\cache.
        /// </summary>
        public static string cache_directory {
            get {
                return ResourceManager.GetString("cache_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon category_marker {
            get {
                object obj = ResourceManager.GetObject("category_marker", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \crash.txt.
        /// </summary>
        public static string crash_file {
            get {
                return ResourceManager.GetString("crash_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод ветвей и границ
        ///Относительно верный результат. Отделяет самые неоптимальные варианты до полного вычисления длины. Требует большого количества оперативной памяти. Рекомендуется для 30 - 40 точек. .
        /// </summary>
        public static string DescriptionBranchBounds {
            get {
                return ResourceManager.GetString("DescriptionBranchBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полный перебор.
        ///Перебор всех возможных маршрутов. Оптимальный результат гарантирован, но требует очень много времени. Рекомендуется использовать при количестве точек меньше 10..
        /// </summary>
        public static string DescriptionFullSearch {
            get {
                return ResourceManager.GetString("DescriptionFullSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жадный алгорим
        ///Действует по принципу жадного человека. Сначала берет наиболее короткие отрезки, затем, которые остаются. Самый быстрый способ, но результат может очень сильно отличаться от идельного. Рекомендуется использовать при очень большом количестве промежуточных точек..
        /// </summary>
        public static string DescriptionGreedy {
            get {
                return ResourceManager.GetString("DescriptionGreedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полярный перебор
        ///Делит все точки на группы и строит оптимальный маршрут через группы. Остальные точки присоединяет &quot;жадным&quot; способом. Чем больше групп, тем работа алгоритма больше похожа на работу полного перебора. При малом количестве групп алгоритм похож на &quot;жадный&quot;. Для количества групп, равном 13, расчет занимает примерно 2 минуты..
        /// </summary>
        public static string DescriptionPolarSearch {
            get {
                return ResourceManager.GetString("DescriptionPolarSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \GMap.NET.Core.dll.
        /// </summary>
        public static string dll_gmapcore {
            get {
                return ResourceManager.GetString("dll_gmapcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \GMap.NET.WindowsForms.dll.
        /// </summary>
        public static string dll_gmapwf {
            get {
                return ResourceManager.GetString("dll_gmapwf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \HtmlAgilityPack.dll.
        /// </summary>
        public static string dll_html_agility_pack {
            get {
                return ResourceManager.GetString("dll_html_agility_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \Lib.dll.
        /// </summary>
        public static string dll_lib {
            get {
                return ResourceManager.GetString("dll_lib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \Newtonsoft.Json.dll.
        /// </summary>
        public static string dll_newtonsoft_json {
            get {
                return ResourceManager.GetString("dll_newtonsoft_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \Res.dll.
        /// </summary>
        public static string dll_res {
            get {
                return ResourceManager.GetString("dll_res", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \ru\TrackConverter.resources.dll.
        /// </summary>
        public static string dll_res_trackconverter {
            get {
                return ResourceManager.GetString("dll_res_trackconverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \ru\ZedGraph.resources.dll.
        /// </summary>
        public static string dll_res_zedgraph {
            get {
                return ResourceManager.GetString("dll_res_zedgraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \System.Runtime.dll.
        /// </summary>
        public static string dll_runtime {
            get {
                return ResourceManager.GetString("dll_runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \System.Data.SQLite.dll.
        /// </summary>
        public static string dll_SQLite {
            get {
                return ResourceManager.GetString("dll_SQLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \x64\SQLite.Interop.dll.
        /// </summary>
        public static string dll_sqliteInterop64 {
            get {
                return ResourceManager.GetString("dll_sqliteInterop64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \x86\SQLite.Interop.dll.
        /// </summary>
        public static string dll_sqliteInterop86 {
            get {
                return ResourceManager.GetString("dll_sqliteInterop86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \ZedGraph.dll.
        /// </summary>
        public static string dll_zed_graph {
            get {
                return ResourceManager.GetString("dll_zed_graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \ICSharpCode.SharpZipLib.dll.
        /// </summary>
        public static string dll_ziplib {
            get {
                return ResourceManager.GetString("dll_ziplib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AIzaSyD_HQaeF2zZDgK7V22BJ_cI-iczZQD-ODo.
        /// </summary>
        public static string google_elevation_api_key {
            get {
                return ResourceManager.GetString("google_elevation_api_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AIzaSyCmDnZ90-2gbv2tpqhkQiXsKM70hvkz3_A.
        /// </summary>
        public static string google_timezone_api {
            get {
                return ResourceManager.GetString("google_timezone_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos; ?&gt;
        ///&lt;gpx  xmlns=&quot;http://www.topografix.com/GPX/1/1&quot;&gt;
        ///  &lt;trk&gt;
        ///    &lt;name&gt;&lt;/name&gt;
        ///    &lt;trkseg&gt;
        ///
        ///	&lt;/trkseg&gt;
        ///  &lt;/trk&gt;
        ///&lt;/gpx&gt;.
        /// </summary>
        public static string gpxschema_scheme_file {
            get {
                return ResourceManager.GetString("gpxschema_scheme_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \Docs\help.html.
        /// </summary>
        public static string help_doc_file {
            get {
                return ResourceManager.GetString("help_doc_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \Images\icons.
        /// </summary>
        public static string icons_directory {
            get {
                return ResourceManager.GetString("icons_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon intermed_point {
            get {
                object obj = ResourceManager.GetObject("intermed_point", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;kml xmlns=&quot;http://earth.google.com/kml/2.2&quot;&gt;
        ///  &lt;Document xmlns=&quot;&quot;&gt;
        ///    &lt;Folder&gt;
        ///      &lt;Folder&gt;
        ///        &lt;name&gt;&lt;/name&gt;
        ///        &lt;open&gt;1&lt;/open&gt;
        ///        &lt;TimeSpan&gt;
        ///          &lt;begin&gt;&lt;/begin&gt;
        ///          &lt;end&gt;&lt;/end&gt;
        ///        &lt;/TimeSpan&gt;
        ///        &lt;Style&gt;
        ///          &lt;ListStyle&gt;
        ///            &lt;listItemType&gt;check&lt;/listItemType&gt;
        ///            &lt;bgColor&gt;00ffffff&lt;/bgColor&gt;
        ///          &lt;/ListStyle&gt;
        ///        &lt;/Style&gt;
        ///        &lt;Placemark&gt;
        ///          &lt;name&gt;&lt;/name&gt;
        ///          &lt;descri [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string kmlschema_scheme_file {
            get {
                return ResourceManager.GetString("kmlschema_scheme_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon main_icon {
            get {
                object obj = ResourceManager.GetObject("main_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon marker {
            get {
                object obj = ResourceManager.GetObject("marker", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon marker_finish {
            get {
                object obj = ResourceManager.GetObject("marker_finish", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon marker_start {
            get {
                object obj = ResourceManager.GetObject("marker_start", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \.
        /// </summary>
        public static string options_folder {
            get {
                return ResourceManager.GetString("options_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;osm version=&apos;0.5&apos; generator=&apos;TrackConverter&apos;&gt;
        ///  
        ///&lt;/osm&gt;.
        /// </summary>
        public static string osmxschema_scheme_file {
            get {
                return ResourceManager.GetString("osmxschema_scheme_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon route_point {
            get {
                object obj = ResourceManager.GetObject("route_point", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon route_point_selected {
            get {
                object obj = ResourceManager.GetObject("route_point_selected", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \saveRoutes.trr.
        /// </summary>
        public static string saveLast_file {
            get {
                return ResourceManager.GetString("saveLast_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon search_result_icon {
            get {
                object obj = ResourceManager.GetObject("search_result_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon selected_point {
            get {
                object obj = ResourceManager.GetObject("selected_point", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \tmp.
        /// </summary>
        public static string temp_directory {
            get {
                return ResourceManager.GetString("temp_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bede91df389731c98287332b289568cad8e7adbbb803c91b3a617e8aa4d05a1b477fdab8b158be77f2259.
        /// </summary>
        public static string VK_access_token {
            get {
                return ResourceManager.GetString("VK_access_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon what_there {
            get {
                object obj = ResourceManager.GetObject("what_there", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 087ECBE0-7869F692-405FA237-852AD116-23CA037A-A588C4C0-2000C58D-5A0D8212.
        /// </summary>
        public static string wikimapia_key {
            get {
                return ResourceManager.GetString("wikimapia_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \Templates\template.dot.
        /// </summary>
        public static string word_template {
            get {
                return ResourceManager.GetString("word_template", resourceCulture);
            }
        }
    }
}
